### create plan 

POST http://localhost:3000/plan
Content-Type: application/json

{"title":"oromie" , "description": "vasl kardan be khazar"}

### get plan by id 

GET  http://localhost:3000/plan/2


### error when post with no title

POST   http://localhost:3000/plan
Content-Type: application/json

{
    "title":""
}
