### create plan 

POST http://localhost:3000/plan
Content-Type: application/json
Authorization: 8e4b8784-be7e-4e1a-8f93-7a6daeab2272

{"title":"oromie" , "description": "vasl kardan be khazar"}

### get plan by id 

GET  http://localhost:3000/plan/2


### error when post with no title

POST   http://localhost:3000/plan
Content-Type: application/json

{
    "title":""
}


### login 

POST http://localhost:3000/login
Content-Type: application/json

{"username":"admin" , "password":"admin"}